aws:
    class: Aws\S3\S3Client
    factory: [Aws\S3\S3Client, 'factory']
    arguments:
        -
            version: latest
            region: eu-west-3
            credentials:
                key: '%env(AWS_KEY)%'

