<?php

namespace App\Controller;

use App\Entity\Issue;
use App\Entity\User;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class NotificationController extends AbstractController
{
    /**
     * @Route("admin/notification", name="notification_index")
     */
    public function index()
    {

        $users = $this->getDoctrine()->getRepository(User::class)->countNotSendedNotification();


        return $this->render('admin/notification/index.html.twig', [
            'users' => $users,
        ]);
    }

    /**
     * Sends mail
     *
     * @Route("admin/notification/send-{id}", name="notification_send", methods="POST")
     * @param Request $request
     * @param User $user
     * @param \Swift_Mailer $mailer
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     * @throws \Exception
     */
    public function sendNotification(Request $request, User $user, \Swift_Mailer $mailer)
    {

//get the token generated by twig form
        $submitedToken = $request->request->get('token');

        if ($this->isCsrfTokenValid('send-notification', $submitedToken)) {

            //get user with only non notified issues from user repository
            $myUser = $this->getDoctrine()->getRepository(User::class)->getNotSendedNotification($user);

            //mail message
            $message = (new \Swift_Message('Equipements prêts, remplacement imminent'))
                ->setFrom('send@exemple.com')
                ->setTo($myUser->getEmail())
            ;

            $myLogo = $message->embed(\Swift_Image::fromPath('img/om.png'));

            $message->setBody(
                    $this->renderView(
                        'admin/notification/email.html.twig',
                        [
                            'user' => $myUser,
                            'image' => $myLogo

                        ]
                    ), 'text/html'
                );
            $mailer->send($message);

            //set the current date to dateMessage
            $date = new \DateTime();

            foreach ($myUser->getissues() as $issue) {
                $issue->setDateMessage($date);

            }

            $this->getDoctrine()->getManager()->flush();
            $this->addFlash('success', 'La notification a été envoyée');
        }

        return $this->redirectToRoute('notification_index');
    }

}
